### PR TITLE
oxcfxics: Uniform hack CNSetRead = CNSetSeen

### PR DESCRIPTION
**Pull request by sixstone-qq**
Until [MS-OXCFXICS] Section 3.2.5.6 be implemented.

### CODE REVIEW

**Comment by blaxter** [comment]
SInce when CnSetRead is the same as CNSetSeen? What I see in the code is CnSetSeen = CnSetSeenFAI.

**Comment by sixstone-qq** [comment]
@blaxter no, it's not. CNSetSeen is for normal messages, CNSetSeenFAI is for FAI messages. Which parts of the code do you see that? If there is any, then there is a bug.

**Comment by blaxter** [comment]
Everywhere, first instance I see, line 1282 oxcfxics.c:

				new_idset = RAWIDSET_convert_to_idset(NULL, sync_data->cnset_seen);
				old_idset = synccontext->cnset_seen_fai;
				/* IDSET_dump (synccontext->cnset_seen, "initial cnset_seen_fai"); */
				synccontext->cnset_seen_fai = IDSET_merge_idsets(synccontext, old_idset, new_idset);

**Comment by sixstone-qq** [comment]
@blaxter in this case it is correct because `sync_data->cnset_seen` is filled with correct data, new CN for FAI messages. It is misleading because it is using the same variable instead of using `sync_data->cnset_seen_fai` but correct in the end.

**Comment by blaxter** [comment]
:ok_hand:

**Pull request merged**
