### PR TITLE
ndr:  fixes for string8 data which contains no-ascii characters

### PR DESCRIPTION
**Pull request by javierag**
This has the following _building_ dependency: https://github.com/zentyal/samba/pull/6

The fixes don't assume samba's DOS encoding anymore. Instead UNIX encoding is used and DOS character set checks removed.

### CODE REVIEW

**Comment by javierag** [comment]
The way to test it is to create a user which has a no-latin display name attribute, create a outlook profile for him and use outlook with it.

**Comment by javierag** [comment]
Also with the build dependency is expected that the test fails.

**Comment by icandigitbaby** [comment]
Please, change _no-ASCII_ for _non-ASCII_ in commit messages.

**Comment by icandigitbaby** [comment]
Besides those minor comments, it's working as a charm :+1:

**Comment by javierag** [comment]
Fixed grammar

**Comment by blaxter** [comment]
I've tested removing the charset attributes on pidl file and it's working perfectly. It provokes a lot of warnings but all of them can be either ignored or fixed with simple casting of pointers.

**Comment by javierag** [comment]
Ok, I will retake this and do the casts

**Comment by blaxter** [comment]
:kissing_cat:

**Comment by javierag** [comment]
Changes done, as expected a lot of lines changed somewhat trivially.

**Pull request merged**
