### PR TITLE
Avoid crash in RAWIDSET_push_eid

### PR DESCRIPTION
**Pull request by icandigitbaby**
`RAWIDSET_find_by_ID` can return NULL without initialising
`last_glob_idset` when the rawidset isn't ID-based. Therefore, if we
pass an ID-based idset to this function it will try to access the `next`
attribute of a NULL pointer, causing a segmentation fault.

### CODE REVIEW

**Comment by javierag** [comment]
It seems legit. There is any way to test it in our systems?

**Comment by blaxter** [comment]
As far as I can see this check is not needed because inside `RAWIDSET_find_by_ID` [there is already this check](https://github.com/zentyal/openchange/pull/213/files#diff-d1e52c35329565e1c0a876b47ffa7c3eR1238) so the function will return `NULL` and no crash can happen

**Comment by blaxter** [comment]
The same can happen on the function below `RAWIDSET_push_guid_glob` with the usage of `RAWIDSET_find_by_GUID`

**Comment by blaxter** [comment]
Btw, I'm :+1: with this because my guess is that you can't reproduce this again.

I think it would be wise to put a log message here (inside the `if(!rawidset ....)`)

**Comment by icandigitbaby** [comment]
@javierag I don't think we've ever hit this case. I realised a check was missing in the code because I tried to push an EID into a GUID-based rawidset (I wasn't fully aware of what I was doing).

**Comment by icandigitbaby** [comment]
I added the return message and also another one in `RAWIDSET_push_guid_glob` (if we're going to return without an error, at least let the log reader know that the operation wasn't performed)

**Comment by blaxter** [comment]
:ok_hand:

**Comment by sixstone-qq** [comment]
Barbaric :+1:

**Pull request merged**
